from datetime import datetime

import streamlit as st
import sqlite3
import pandas as pd
from datetime import datetime   # <-- ADD THIS LINE



# -*- coding: utf-8 -*-
"""Untitled29.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AcyUKTFgX-IcdZQ6YLbpNLO6zG6HENdO
"""

import sqlite3

DB_PATH = "yourapp.db"

def init_db():
    conn = sqlite3.connect(DB_PATH)
    c = conn.cursor()
    c.execute('''
        CREATE TABLE IF NOT EXISTS users (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            email TEXT UNIQUE, password TEXT, role TEXT
        )''')
    c.execute('''
        CREATE TABLE IF NOT EXISTS queries (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            user_email TEXT,
            query_text TEXT,
            language TEXT,
            generated_code TEXT,
            timestamp TEXT
        )''')
    c.execute('''
        CREATE TABLE IF NOT EXISTS feedback (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            user_email TEXT,
            query_id INTEGER,
            rating INTEGER,
            comment TEXT,
            timestamp TEXT
        )''')
    conn.commit()
    conn.close()
init_db()

import streamlit as st

if "useremail" not in st.session_state:
    st.session_state.useremail = ""
if "role" not in st.session_state:
    st.session_state.role = None
if "logged_in" not in st.session_state:
    st.session_state.logged_in = False

def register_user(email, password, role):
    conn = sqlite3.connect(DB_PATH)
    c = conn.cursor()
    try:
        c.execute("INSERT INTO users (email, password, role) VALUES (?, ?, ?)", (email, password, role))
        conn.commit()
    except sqlite3.IntegrityError:
        conn.close()
        return False
    conn.close()
    return True

def valid_login(email, password):
    conn = sqlite3.connect(DB_PATH)
    c = conn.cursor()
    c.execute("SELECT role FROM users WHERE email=? AND password=?", (email, password))
    row = c.fetchone()
    conn.close()
    if row:
        return row[0]
    return None

def show_login():
    st.title("Dashboards and Code Assistants")
    st.subheader("Login")
    email = st.text_input("Email")
    password = st.text_input("Password", type="password")
    if st.button("Sign In"):
        role = valid_login(email, password)
        if role:
            st.session_state.useremail = email
            st.session_state.role = role
            st.session_state.logged_in = True
            st.success(f"Logged in as {email} ({role})")
            st.experimental_rerun()
        else:
            st.error("Invalid credentials.")
    st.subheader("Register")
    reg_email = st.text_input("New Email")
    reg_pw = st.text_input("New Password", type="password")
    reg_role = st.selectbox("Role", ["User", "Admin"])
    if st.button("Create Account"):
        if register_user(reg_email, reg_pw, reg_role):
            st.success("Account created! You can now log in.")
        else:
            st.error("That email is already registered.")

if not st.session_state.logged_in:
    show_login()

# Commented out IPython magic to ensure Python compatibility.
# %pip install streamlit

if st.session_state.logged_in:
    page = st.sidebar.selectbox("Go to", ["Code Assistants", "Admin Dashboard", "My History", "Logout"])
else:
    page = "Login / Register"

def log_query(user_email, query_text, language, generated_code):
    conn = sqlite3.connect(DB_PATH)
    c = conn.cursor()
    c.execute('''INSERT INTO queries (user_email, query_text, language, generated_code, timestamp)
                 VALUES (?, ?, ?, ?, ?)''',
                 (user_email, query_text, language, generated_code, datetime.utcnow().isoformat()))
    query_id = c.lastrowid
    conn.commit()
    conn.close()
    return query_id

def submit_feedback(user_email, query_id, rating, comment):
    conn = sqlite3.connect(DB_PATH)
    c = conn.cursor()
    c.execute('''INSERT INTO feedback (user_email, query_id, rating, comment, timestamp)
                 VALUES (?, ?, ?, ?, ?)''',
                 (user_email, query_id, rating, comment, datetime.utcnow().isoformat()))
    conn.commit()
    conn.close()

if page == "Code Assistants":
    st.title("Dashboards and Code Assistants")
    user_email = st.session_state.useremail
    language = st.selectbox("Choose language", ["Python", "JavaScript", "SQL"])
    query_text = st.text_input("Enter your code prompt")
    if st.button("Generate Code"):
        generated_code = "def sample():\n    pass" # Replace with real output
        st.code(generated_code, language)
        query_id = log_query(user_email, query_text, language, generated_code)
        st.markdown("**Leave Feedback for This Output:**")
        rating = st.slider("Rating", 1, 5)
        comment = st.text_area("Feedback")
        if st.button("Submit Feedback"):
            submit_feedback(user_email, query_id, rating, comment)
            st.success("Feedback submitted!")

def get_user_history(user_email):
    conn = sqlite3.connect(DB_PATH)
    c = conn.cursor()
    c.execute('''SELECT query_text, language, generated_code, timestamp FROM queries
                 WHERE user_email=? ORDER BY timestamp DESC''', (user_email,))
    history = c.fetchall()
    conn.close()
    return history

if page == "My History":
    st.title("Your Output History")
    for qtext, lang, gcode, ts in get_user_history(st.session_state.useremail):
        st.info(f"{ts}: [{lang}] {qtext}")
        st.code(gcode, lang)

def get_trending_queries():
    conn = sqlite3.connect(DB_PATH)
    df = pd.read_sql_query(
        "SELECT query_text, COUNT(*) as count FROM queries GROUP BY query_text ORDER BY count DESC LIMIT 5",
        conn)
    conn.close()
    return df

def get_language_stats():
    conn = sqlite3.connect(DB_PATH)
    df = pd.read_sql_query(
        "SELECT language, COUNT(*) as count FROM queries GROUP BY language ORDER BY count DESC",
        conn)
    conn.close()
    return df

def get_feedback_stats():
    conn = sqlite3.connect(DB_PATH)
    df = pd.read_sql_query(
        "SELECT rating, COUNT(*) as count FROM feedback GROUP BY rating ORDER BY rating",
        conn)
    avg = pd.read_sql_query("SELECT AVG(rating) as avg_rating FROM feedback", conn).iloc[0, 0]
    conn.close()
    return df, avg

if page == "Admin Dashboard" and st.session_state.role == "Admin":
    st.title("Admin Dashboard")
    st.subheader("Trending Queries")
    trends = get_trending_queries()
    st.dataframe(trends)
    st.subheader("Language Usage")
    lang_stats = get_language_stats()
    st.bar_chart(lang_stats.set_index('language'))
    st.subheader("Feedback Stats")
    fb_stats, avg_fb = get_feedback_stats()
    st.bar_chart(fb_stats.set_index('rating'))
    if avg_fb is not None:
        st.success(f"Average Feedback Rating: {avg_fb:.2f}/5")
    else:
        st.info("No average rating yet.")
elif page == "Admin Dashboard":
    st.warning("Only admins can view this page.")

if page == "Logout":
    st.session_state.logged_in = False
    st.session_state.useremail = ""
    st.session_state.role = None
    st.success("Logged out.")
    st.experimental_rerun()

import pandas as pd

import streamlit as st
import sqlite3
import pandas as pd   # <-- ADD THIS if it's missing
from datetime import datetime

