# -*- coding: utf-8 -*-
"""code generation with UIs and visualization

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1icEsLSUvNren8QMMSBfawJSB4Sgc9lhY
"""

!pip install transformers torch ipywidgets radon matplotlib
!pip install ipywidgets
!pip install torch
!pipn install transformers
!pip install AutoTokenizer

"""1.DeepSeek-Coder-1.3B"""

from transformers import AutoTokenizer, AutoModelForCausalLM

tokenizer_ds = AutoTokenizer.from_pretrained("deepseek-ai/deepseek-coder-1.3b-instruct")
model_ds = AutoModelForCausalLM.from_pretrained("deepseek-ai/deepseek-coder-1.3b-instruct")

"""2. Phi-2-2.7B"""

tokenizer_phi = AutoTokenizer.from_pretrained("microsoft/phi-2")
model_phi = AutoModelForCausalLM.from_pretrained("microsoft/phi-2")

"""3. Gemma-2B-IT"""

from transformers import AutoTokenizer, AutoModelForCausalLM
tokenizer_gemma = AutoTokenizer.from_pretrained("google/gemma-2b-it", trust_remote_code=True)
model_gemma = AutoModelForCausalLM.from_pretrained("google/gemma-2b-it", trust_remote_code=True)

"""4.Stable-Code-3B

"""

from transformers import AutoTokenizer, AutoModelForCausalLM
tokenizer_stable = AutoTokenizer.from_pretrained("stabilityai/stable-code-3b")
model_stable = AutoModelForCausalLM.from_pretrained("stabilityai/stable-code-3b")

"""5.Replit-Code-3B

"""

from transformers import AutoTokenizer, AutoModelForCausalLM
tokenizer_replit = AutoTokenizer.from_pretrained("replit/replit-code-v1-3b")
model_replit = AutoModelForCausalLM.from_pretrained("replit/replit-code-v1-3b")

"""excecuting all the five codes in one code"""

prompt = "Write a Python function to check if a number is prime."

def generate_code(prompt, tokenizer, model):
    inputs = tokenizer(prompt, return_tensors="pt")
    outputs = model.generate(inputs.input_ids, max_new_tokens=256)
    code = tokenizer.decode(outputs[0], skip_special_tokens=True)
    return code

print("=== DeepSeek-Coder ===")
print(generate_code(prompt, tokenizer_ds, model_ds))

print("=== Phi-2 ===")
print(generate_code(prompt, tokenizer_phi, model_phi))

print("=== Gemma ===")
print(generate_code(prompt, tokenizer_gemma, model_gemma))

print("=== Stable-Code ===")
print(generate_code(prompt, tokenizer_stable, model_stable))

print("=== Replit-Code ===")
print(generate_code(prompt, tokenizer_replit, model_replit))

"""10 sample code prompts from differnt domains

1.Bubble Sort
"""

def bubble_sort(arr):
    n = len(arr)
    for i in range(n):
        for j in range(0, n - i - 1):
            if arr[j] > arr[j + 1]:
                arr[j], arr[j + 1] = arr[j + 1], arr[j]
    return arr

"""2.Linked list Class"""

class Node:
    def __init__(self, data):
        self.data = data
        self.next = None

class LinkedList:
    def __init__(self):
        self.head = None

    def insert(self, data):
        new_node = Node(data)
        if not self.head:
            self.head = new_node
        else:
            temp = self.head
            while temp.next:
                temp = temp.next
            temp.next = new_node

    def display(self):
        temp = self.head
        while temp:
            print(temp.data, end=" ")
            temp = temp.next
        print()

"""3.Check prime"""

def is_prime(num):
    if num <= 1:
        return False
    for i in range(2, int(num**0.5)+1):
        if num % i == 0:
            return False
    return True

"""4.Palindrome String"""

def is_palindrome(s):
    return s == s[::-1]

"""5.Word Count in File"""

def count_words(filename):
    with open(filename, 'r') as f:
        text = f.read()
    return len(text.split())

"""6.Web Scraping with BeautifulSoup"""

import requests
from bs4 import BeautifulSoup

url = "https://example.com"
response = requests.get(url)
soup = BeautifulSoup(response.text, 'html.parser')

headings = [h.get_text() for h in soup.find_all(['h1', 'h2', 'h3', 'h4', 'h5', 'h6'])]
print(headings)

"""7.SQL Query (Employees table)


"""

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT name FROM Employees WHERE salary > 50000;

"""Now you can use the `%%sql` magic command followed by your SQL query. You will need to provide a database connection string. Here's an example using an in-memory SQLite database:

To run SQL queries in Colab, you can use the `%%sql` cell magic command. First, you need to install and load the `ipython-sql` extension.
"""

# Commented out IPython magic to ensure Python compatibility.
!pip install ipython-sql
# %load_ext sql

"""Now you can use the `%%sql` magic command followed by your SQL query. You will need to provide a database connection string. Here's an example using an in-memory SQLite database:"""

# Commented out IPython magic to ensure Python compatibility.
# %sql sqlite:///:memory:

"""8.Car Class with Methods"""

class Car:
    def __init__(self, make, model):
        self.make = make
        self.model = model

    def start_engine(self):
        print("Engine started.")

    def display_details(self):
        print(f"Car: {self.make} {self.model}")

"""9.Division by Zero Exception Handling"""

def safe_divide(a, b):
    try:
        return a / b
    except ZeroDivisionError:
        return "Cannot divide by zero"

"""10.Bar Chart with Matplotlib"""

import matplotlib.pyplot as plt

fruits = ['Apple', 'Banana', 'Orange', 'Mango', 'Grapes']
sales = [100, 80, 70, 60, 50]

plt.bar(fruits, sales)
plt.xlabel("Fruits")
plt.ylabel("Sales")
plt.title("Fruit Sales")
plt.show()

"""UIS:Benchmark All models"""

import ipywidgets as widgets
from IPython.display import display, clear_output

prompt_input = widgets.Textarea(value="Write a Python function to compute the nth Fibonacci number.", description="Prompt:", layout=widgets.Layout(width="90%"))
run_button = widgets.Button(description="Generate (All Models)")
output_area = widgets.Output()

def run_all_models(b):
    with output_area:
        clear_output()
        results = {}
        for name, (tok, mod) in model_objects.items():
            print(f"\n=== {name} ===\n")
            code = generate_code(prompt_input.value, tok, mod, name)
            print(code)
            metrics_ = evaluate_code_metrics(code)
            print("\nMetrics:", metrics_,"\n","-"*80)
            results[name] = {"code": code, "metrics": metrics_}
        b.results = results

run_button.on_click(run_all_models)
display(prompt_input, run_button, output_area)

"""2.Model Selector Cell"""

selector = widgets.SelectMultiple(options=list(model_objects.keys()), value=tuple(model_objects.keys()), description='Models:', layout=widgets.Layout(width="50%"))
prompt_input2 = widgets.Textarea(value="Write a JavaScript function to sort an array.", description="Prompt:", layout=widgets.Layout(width="90%"))
run_button2 = widgets.Button(description="Generate (Selected Models)")
output_area2 = widgets.Output()

def run_selected_models(b):
    with output_area2:
        clear_output()
        for name in selector.value:
            tok, mod = model_objects[name]
            print(f"\n=== {name} ===\n")
            code = generate_code(prompt_input2.value, tok, mod, name)
            print(code)
            metrics_ = evaluate_code_metrics(code)
            print("\nMetrics:", metrics_,"\n","-"*80)
run_button2.on_click(run_selected_models)
display(prompt_input2, selector, run_button2, output_area2)