# -*- coding: utf-8 -*-
"""milestone 3 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jqxYXroxWSYJUAdJd75qoCWmSN6pyuqi
"""

import jwt
import datetime
from flask import Flask, request, jsonify

app = Flask(__name__)
SECRET_KEY = "your_secret_key"

def encode_auth_token(user_id, role):
    payload = {
        'exp': datetime.datetime.utcnow() + datetime.timedelta(days=1),
        'iat': datetime.datetime.utcnow(),
        'sub': user_id,
        'role': role
    }
    return jwt.encode(payload, SECRET_KEY, algorithm='HS256')

@app.route('/login', methods=['POST'])
def login():
    data = request.json
    # Validate user and password from DB
    user_id, role = 'dummy_id', 'user'  # Replace with DB check
    token = encode_auth_token(user_id, role)
    return jsonify({"token": token})

import streamlit as st

# Simple user database for demo
users = {"user@example.com": "password123"}

st.title("CodeGenie - Login/Register")
email = st.text_input("Email")
password = st.text_input("Password", type="password")

if st.button("Sign In"):
    if email in users and users[email] == password:
        st.success("Signed In!")
    else:
        st.error("Invalid email or password.")

if st.button("Register"):
    if email in users:
        st.warning("User already exists!")
    else:
        users[email] = password
        st.success("Registered successfully! Now you can sign in.")

# You can expand with persistent database and JWT for production

# Commented out IPython magic to ensure Python compatibility.
# %pip install streamlit

import streamlit as st

# Simple user database for demo
users = {"user@example.com": "password123"}

st.title("CodeGenie - Login/Register")
email = st.text_input("Email")
password = st.text_input("Password", type="password")

if st.button("Sign In"):
    if email in users and users[email] == password:
        st.success("Signed In!")
    else:
        st.error("Invalid email or password.")

if st.button("Register"):
    if email in users:
        st.warning("User already exists!")
    else:
        users[email] = password
        st.success("Registered successfully! Now you can sign in.")

# You can expand with persistent database and JWT for production

def calculate_sum(a, b):
    return a + b

# Explanation for UI or API
explanation = "This function takes two parameters a and b and returns their sum."